export const FETCH_ALL_IMAGES = 'FETCH_ALL_IMAGES';
export const STORE_ALL_IMAGES = 'STORE_ALL_IMAGES';
export const VIEW_SELECTED_IMAGE = 'VIEW_SELECTED_IMAGE';
export const RESET_SELECTED_IMAGE = 'RESET_SELECTED_IMAGE';
